### ISSUE TITLE
InfinispanCacheMeterBinder throws NullPointerException when statistics-available="false"

### ISSUE THREAD

**Issue by ecostanzi** [infinispan/infinispan-spring-boot#123]
**Describe the bug**
When statistics-available="false" the following exception occurs.
```
Caused by: java.lang.NullPointerException: null
	at org.infinispan.stats.impl.StatsImpl.<init>(StatsImpl.java:54) ~[infinispan-core-9.4.15.Final.jar:9.4.15.Final]
	at org.infinispan.cache.impl.CacheImpl.getStats(CacheImpl.java:1405) ~[infinispan-core-9.4.15.Final.jar:9.4.15.Final]
	at org.infinispan.cache.impl.AbstractDelegatingAdvancedCache.getStats(AbstractDelegatingAdvancedCache.java:301) ~[infinispan-core-9.4.15.Final.jar:9.4.15.Final]
	at org.infinispan.spring.starter.embedded.actuator.InfinispanCacheMeterBinder.size(InfinispanCacheMeterBinder.java:31) ~[infinispan-spring-boot-starter-embedded-2.1.7.Final.jar:na]
```

**To Reproduce**
1. Clone this repo https://github.com/ecostanzi/spring-boot-infinispan-hibernate
2. run `./mvnw spring-boot:start`
3. The exception above is thrown

**Temporary Fix**
Change the CacheConfiguration by setting enabled(true):
```java
@Bean
    public InfinispanCacheConfigurer cacheConfigurer() {

        return manager -> {
            // initialize application cache
            manager.defineConfiguration("spring-cache", new ConfigurationBuilder()
                    .clustering().cacheMode(CacheMode.DIST_SYNC).hash().numOwners(2)
                    .jmxStatistics().enabled(false)
                    .available(true)// now stats are available
                    .eviction()
                    .type(EvictionType.COUNT).size(1000).expiration()
                    .lifespan(1, TimeUnit.MINUTES).build());

            setCacheManager(manager);
        };
    }
```

**Expected behavior**
When `statistics-available="false" the InfinispanCacheMeterBinder should either not be invoked or should handle the case when that getStats() throws the exception.

**Additional context**
- When using a custom region class the exception is thrown because the getStats() method returns null (to reproduce, clone branch `custom-region-factory` of the above repo):
```
Caused by: java.lang.NullPointerException: null
	at org.infinispan.spring.starter.embedded.actuator.InfinispanCacheMeterBinder.size(InfinispanCacheMeterBinder.java:31) ~[infinispan-spring-boot-starter-embedded-2.1.7.Final.jar:na]
	at io.micrometer.core.instrument.binder.cache.CacheMeterBinder.bindTo(CacheMeterBinder.java:50) ~[micrometer-core-1.1.5.jar:1.1.5]
	at org.springframework.boot.actuate.metrics.cache.CacheMetricsRegistrar.bindCacheToRegistry(CacheMetricsRegistrar.java:65) ~[spring-boot-actuator-2.1.7.RELEASE.jar:2.1.7.RELEASE]
```

**Comment by karesti** [comment]
I've opened the issue: https://issues.jboss.org/browse/ISPN-10712
Will be fixed on the next release with the upgrade of SB version
Thank you!
