### ISSUE TITLE
InfinispanCacheMeterBinder throws NullPointerException when statistics-available="false"

### ISSUE THREAD

**Issue by asmirnou** [infinispan/infinispan-spring-boot#161]
**Describe the bug**

When cache is _simple_, statistics is not _available_ and Infinispan embedded metrics are exposed using Micrometer, the following exception occurs:

```
Caused by: java.lang.NullPointerException: null
	at org.infinispan.spring.starter.embedded.actuator.InfinispanCacheMeterBinder.size(InfinispanCacheMeterBinder.java:31) ~[infinispan-spring-boot-starter-embedded-2.3.4.Final.jar:2.3.4.Final]
	at io.micrometer.core.instrument.binder.cache.CacheMeterBinder.bindTo(CacheMeterBinder.java:49) ~[micrometer-core-1.5.6.jar:1.5.6]
	at org.springframework.boot.actuate.metrics.cache.CacheMetricsRegistrar.bindCacheToRegistry(CacheMetricsRegistrar.java:65) ~[spring-boot-actuator-2.3.5.RELEASE.jar:2.3.5.RELEASE]
```

**To Reproduce**

1. Clone this repo https://github.com/asmirnou/infinispan-spring-boot-npe
2. Run `./gradlew bootRun`
3. The exception above is thrown

**Expected behavior**

`InfinispanCacheMeterBinder` handles the case when `getStats()` returns `null` if cache is of type `SimpleCacheImpl`.

**Additional context**

The situation simulated in the demo project occurs in a real Spring Boot application when [Hibernate 2nd level cache default configurations](https://github.com/infinispan/infinispan/blob/master/hibernate/cache-commons/src/main/resources/org/infinispan/hibernate/cache/commons/builder/infinispan-configs.xml) are used and Micrometer metrics are present.

```
<local-cache-configuration name="pending-puts" simple-cache="true" statistics="false" statistics-available="false">
```

**Comment by karesti** [comment]
thank you @asmirnou ! I will open a jira
