### ISSUE TITLE
Complete configuration for remote sessions

### ISSUE THREAD

**Issue by vadimkim** [infinispan/infinispan-spring-boot#45]
Hello,
    I have Infinispan remote cluster with "mySessions" cache to store HTTP sessions. Following the documentation I did:
1. Added this project to maven dependencies
2. Added spring-sessions to maven dependencies
3. Added hotrod.configuration.Configuration bean with connection parameters to remote (Hotrod client used with authentication and TLS)
4. Added `@EnableCaching` and `@EnableInfinispanRemoteHttpSession` to controller

Got this error during start-up:

`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionRepository' defined in class path resource [org/infinispan/spring/session/configuration/InfinispanRemoteHttpSessionConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.infinispan.spring.session.InfinispanRemoteSessionRepository]: Factory method 'sessionRepository' threw exception; nested exception is org.infinispan.client.hotrod.exceptions.TransportException:: ISPN004071: Connection to 192.168.99.100:11222 was closed while waiting for response.
`
I am afraid my dependency tree is incorrect. Here what I have now:
```
      <dependencies>
		<dependency>
			<groupId>org.infinispan</groupId>
			<artifactId>infinispan-spring-boot-starter-remote</artifactId>
			<version>2.0.0.Alpha1</version>
		</dependency>
		<dependency>
			<groupId>org.infinispan</groupId>
			<artifactId>infinispan-spring4-remote</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-tomcat</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jetty</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.session</groupId>
			<artifactId>spring-session</artifactId>
			<version>${spring-session.version}</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

```
Is this correct?

**Comment by slaskawi** [comment]
The main problem is located here:

```
org.infinispan.client.hotrod.exceptions.TransportException:: ISPN004071: Connection to 192.168.99.100:11222 was closed while waiting for response.
```

Could you please run `mvn dependency:tree` and verify if the Hot Rod client artifact version matches your server?

**Comment by vadimkim** [comment]
I got this:
```
[INFO] |  \- org.infinispan:infinispan-client-hotrod:jar:9.2.0.Final:compile
[INFO] |     +- org.infinispan:infinispan-commons:jar:9.2.0.Final:compile
[INFO] |     |  \- com.github.ben-manes.caffeine:caffeine:jar:2.4.0:compile
[INFO] |     +- org.jboss.marshalling:jboss-marshalling-osgi:jar:2.0.2.Final:compile
[INFO] |     +- io.netty:netty-handler:jar:4.1.21.Final:compile
[INFO] |     |  +- io.netty:netty-buffer:jar:4.1.21.Final:compile
[INFO] |     |  +- io.netty:netty-transport:jar:4.1.21.Final:compile
[INFO] |     |  |  \- io.netty:netty-resolver:jar:4.1.21.Final:compile
[INFO] |     |  \- io.netty:netty-codec:jar:4.1.21.Final:compile
[INFO] |     \- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.21.Final:compile
[INFO] |        +- io.netty:netty-common:jar:4.1.21.Final:compile
[INFO] |        \- io.netty:netty-transport-native-unix-common:jar:4.1.21.Final:compile
[INFO] +- org.infinispan:infinispan-spring4-remote:jar:9.2.0.Final:compile
[INFO] |  \- org.infinispan:infinispan-spring4-common:jar:9.2.0.Final:compile
```
I am also using infinispan 9.2.0.Final version. Manual test with remote cache manager works. I have simple POJO class inside this project with main() methods that calls Infinispan directly.

**Comment by slaskawi** [comment]
Ok, everything looks good. 

Would you be able to build a small reproducer for me? So that I could run it against `docker run jboss/infinispan-server:9.2.0.Final`.

**Comment by vadimkim** [comment]
I think it is easier to start from manual test and create spring boot configuration that does exactly the same. Here it manual working test:

```
public class ManualTest {
        public static void main(String[] args) {
            // Create a configuration for a locally-running server
            ClassLoader tccl = Thread.currentThread().getContextClassLoader();
            ConfigurationBuilder builder = new ConfigurationBuilder();
            builder.socketTimeout(1000)
                   .connectionTimeout(1000)
                   .addServer().host("192.168.99.100")
                   .security()
                     .ssl()
                        .enable()
                        .trustStoreFileName(tccl.getResource("truststore.jks").getPath())
                        .trustStorePassword("storePass".toCharArray())
                     .authentication()
                        .enable()
                        .saslMechanism("PLAIN")
                        .callbackHandler(new TestCallHandler("user", "LdapRealm", "password".toCharArray()));

            // Connect to the server
            RemoteCacheManager cacheManager = new RemoteCacheManager(builder.build());
            // Obtain the remote cache
            RemoteCache<String, MapSession> cache = cacheManager.getCache("mySessions");
            Map<String, String> stats = cache.stats().getStatsMap();
            System.out.println(stats);
            CloseableIteratorSet<String> entries = cache.keySet();
            for (String entry: entries) {
                System.out.println("Entry: " + entry);
                MapSession data = cache.get(entry);
                for (String attribute: data.getAttributeNames()) {
                    System.out.println("Attribute " + attribute + ": " + data.getAttribute(attribute).toString());
                }
            }
        }
}
```
TestCallHadler class:
```
public class TestCallHandler implements CallbackHandler {
    final private String username;
    final private char[] password;
    final private String realm;

    public TestCallHandler(String username, String realm, char[] password) {
        this.username = username;
        this.password = password;
        this.realm = realm;
    }

    public void handle(Callback[] callbacks) throws IOException, UnsupportedCallbackException {
        for (Callback callback : callbacks) {
            if (callback instanceof NameCallback) {
                NameCallback nameCallback = (NameCallback) callback;
                nameCallback.setName(username);
            } else if (callback instanceof PasswordCallback) {
                PasswordCallback passwordCallback = (PasswordCallback) callback;
                passwordCallback.setPassword(password);
            } else if (callback instanceof AuthorizeCallback) {
                AuthorizeCallback authorizeCallback = (AuthorizeCallback) callback;
                authorizeCallback.setAuthorized(authorizeCallback.getAuthenticationID().equals(
                        authorizeCallback.getAuthorizationID()));
            } else if (callback instanceof RealmCallback) {
                RealmCallback realmCallback = (RealmCallback) callback;
                realmCallback.setText(realm);
            } else {
                throw new UnsupportedCallbackException(callback);
            }
        }
    }
}
```
Basically I need the same, but with spring boot and annotations. If you need Infinispan cloud.xml -- let me know - I will upload it somewhere. It is rather big

**Comment by vadimkim** [comment]
Here how I customized the bean:
```
@Configuration
public class InfinispanConfiguration {


    @Bean
    public org.infinispan.client.hotrod.configuration.Configuration customConfiguration() {
        ClassLoader tccl = Thread.currentThread().getContextClassLoader();
        return new ConfigurationBuilder()
                .addServer()
                .host("192.168.99.100")
                .security()
                .ssl()
                .enable()
                .trustStoreFileName(tccl.getResource("truststore.jks").getPath())
                .trustStorePassword("storePass".toCharArray())
                .authentication()
                .enable()
                .saslMechanism("PLAIN")
                .callbackHandler(new TestCallHandler("user", "LdapRealm", "password".toCharArray()))
                .build();
    }
}
```

**Comment by vadimkim** [comment]
And the Controller
```
@RestController
@RequestMapping("/api")
@EnableCaching
@EnableInfinispanRemoteHttpSession
public class UserSessionController {
    private final SpringRemoteCacheManager cacheManager;

    @Autowired
    public UserSessionController(SpringRemoteCacheManager cacheManager) {
        this.cacheManager = cacheManager;
    }

    @Autowired
    private UserSessionData sessionData;

    @GetMapping(value = "/get-data", produces = MediaType.TEXT_PLAIN_VALUE)
    public String getData() {
        Set entries = cacheManager.getCache("mySessions").getNativeCache().keySet();
        Cache.ValueWrapper data = null;
        for (Object entry : entries) {
            data = cacheManager.getCache("mySessions").get(entry);
        }
        return "Saved data: " + data.toString();
    }
}
```

**Comment by slaskawi** [comment]
I'm not an authentication expert (maybe @tristantarrant could chime in) but could you please simplify the authentication configuration to something like this:

```
Configuration c = new ConfigurationBuilder()
            .addServer()
                .host(HOT_ROD_ENDPOINT_SERVICE)
                .port(11222)
               .security()
                .authentication().enable()
                  .username(USERNAME)
                  .password(PASSWORD)
                  .realm("ApplicationRealm")
                  .saslMechanism("DIGEST-MD5")
                  .saslQop(SaslQop.AUTH)
                .ssl().enable()
                  .trustStoreFileName(TRUSTSTORE_PATH)
                  .trustStorePassword(TRUSTSTORE_PASSWORD)
            .build();
```

I have a gut feeling that the error message you see is connected to authentication somehow. If that won't work I'll try to check it tomorrow or on Tuesday...

**Comment by vadimkim** [comment]
@slaskawi due to easter holiday I will be able to do the test again on Monday. I also have a feeling that it is a kind of protocol mismatch or truststore is not loaded correctly. I don't want to disturb @tristantarrant with such a small configuration problem unless this issue is really connected to infinispan.

**Comment by slaskawi** [comment]
I created a complete reproducer of this case here: https://github.com/slaskawi/infinispan-spring-session-reproducer-45

It seems that project configuration is correct. Spring Boot Starter correctly works with Spring Session. The reason this doesn't work must be either in Authentication or Encryption. I would advice turning encryption off and trying out authentication. If that works, try encryption and authentication turned off.

**Comment by vadimkim** [comment]
@slaskawi Thank you for the example! It makes me to go a bit further. Now I am sure that problem is somehwere at encryption. On the server side when I enable SSL/TLS I got this:
```
07:51:54,210 ERROR [org.infinispan.server.hotrod.CacheDecodeContext] (HotRod-ServerWorker-5-3) ISPN005003: Exception reported: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: a0040b17126f6e626f617264696e6753657373696f6e730003ffffffff0f00
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1138)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1202)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:236)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:494)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)

```

**Comment by vadimkim** [comment]
I have found the error:  If application has hotrod-client.properties file at resources that information overrides the Configuration of the application. Particualrly this class/method has a problem:

> InfinispanRemoteAutoConfiguration class 
> public RemoteCacheManager remoteCacheManager() throws IOException {} method.
>  
Since it is not possible to define SSL/TLS settings (or authentication) at hotrod-client.properties I think this information should be either merge-d or some preference should be defined. May be user warning is also good thing to issue.
At the moment I have removed hotrod-client.properties file and application starts to work correctly

**Comment by vadimkim** [comment]
I have created pull-request. The main idea is - if there is a remote configuration defined by `@Bean` then hotrod-client.properties and all other variants are ignored. 
I think merge logic is more complex and error prone and should be avoided.
