### ISSUE TITLE
No CacheResolver specified, and no unique bean of type CacheManager found

### ISSUE THREAD

**Issue by vadimkim** [infinispan/infinispan-spring-boot#53]
I have Spring Boot application with HttpSession support. It runs with local _development_ profile and `@EnableInfinispanEmbeddedHttpSession ` successfully. For production we use _kubernetes_ profile and `@EnableInfinispanRemoteHttpSession` to connect to remote Infinispan cluster. Connection to the server is made, but cache manager seems to be duplicated (as I understood)
```
2018-07-25 14:54:45.256  WARN 5 --- [           main] o.i.manager.DefaultCacheManager          : [] [] ISPN000435: Cache manager initialized with a default cache configuration but without a name for it. Set it in the GlobalConfiguration.
2018-07-25 14:54:46.983  INFO 5 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : [] [] Mapped "{[/management/health || /management/health.json],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.HealthMvcEndpoint.invoke(javax.servlet.http.HttpServletRequest,java.security.Principal)
2018-07-25 14:54:46.984  INFO 5 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : [] [] Mapped "{[/management/info || /management/info.json],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
2018-07-25 14:54:47.089  INFO 5 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : [] [] Initializing ExecutorService  'assyncExecutor'
2018-07-25 14:54:47.785 DEBUG 5 --- [           main] o.i.c.h.i.t.netty.ChannelFactory         : [] [] Statically configured servers: [172.31.86.57:11222]
2018-07-25 14:54:47.785 DEBUG 5 --- [           main] o.i.c.h.i.t.netty.ChannelFactory         : [] [] Tcp no delay = true; client socket timeout = 5000 ms; connect timeout = 5000 ms
2018-07-25 14:54:47.786 DEBUG 5 --- [           main] o.i.c.h.i.t.netty.ChannelFactory         : [] [] Creating new channel pool for 172.31.86.57:11222
2018-07-25 14:54:47.828  INFO 5 --- [nt-async-pool-1] o.i.client.hotrod.impl.protocol.Codec21  : [] [] ISPN004006: Server sent new topology view (id=5, age=0) containing 2 addresses: [172.31.86.57:11222]
2018-07-25 14:54:47.829 DEBUG 5 --- [nt-async-pool-1] o.i.c.h.i.t.netty.ChannelFactory         : [] [] Same list of servers, not changing the pool
2018-07-25 14:54:47.833  INFO 5 --- [           main] o.i.client.hotrod.RemoteCacheManager     : [] [] ISPN004021: Infinispan version: 9.3.1.Final
2018-07-25 14:54:48.802  INFO 5 --- [           main] utoConfigurationReportLoggingInitializer : [] [] 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2018-07-25 14:54:48.812 ERROR 5 --- [           main] o.s.boot.SpringApplication               : [] [] Application startup failed

java.lang.IllegalStateException: No CacheResolver specified, and no unique bean of type CacheManager found. Mark one as primary (or give it the name 'cacheManager') or declare a specific CacheManager to use, that serves as the default one.
	at org.springframework.cache.interceptor.CacheAspectSupport.afterSingletonsInstantiated(CacheAspectSupport.java:209)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:781)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at ee.cooppank.onboardingweb.OnboardingwebApp.main(OnboardingwebApp.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
```
My cache configuration class is:

```
@Profile("kubernetes")
@Configuration
@EnableCaching
@EnableInfinispanRemoteHttpSession(cacheName = "mysessions")
public class CacheConfiguration {

    private final Logger log = LoggerFactory.getLogger(this.getClass());
    private final ApplicationProperties appProperties;
    private final InfinispanProperties cacheProperties;
    private final static String truststorePath = "/etc/secrets/truststore.jks";

    public CacheConfiguration (ApplicationProperties appProperties, InfinispanProperties cacheProperties) {
        this.appProperties = appProperties;
        this.cacheProperties = cacheProperties;
    }

    @Bean
    public InfinispanRemoteConfigurer infinispanRemoteConfigurer() {
        return () -> new ConfigurationBuilder()
            .addServers(cacheProperties.getServerList())
            .socketTimeout(cacheProperties.getSocketTimeout())
            .connectionTimeout(cacheProperties.getConnectTimeout())
            .security()
               .ssl().enable()
                     .trustStoreFileName(truststorePath)
                     .trustStoreType("jks")
                     .trustStorePassword(appProperties.getTruststorePassword().toCharArray())
            .build();
    }

    @Bean
    public SpringRemoteCacheManagerFactoryBean springCache() {
        log.info("Remote infinispan session cache activated...");
        SpringRemoteCacheManagerFactoryBean bean = new SpringRemoteCacheManagerFactoryBean();
        bean.setConfigurationProperties(infinispanRemoteConfigurer().getRemoteConfiguration().properties());
        return bean;
    }

}
```

Please give a hint to how resolve this issue correctly?

**Comment by vadimkim** [comment]
I was able to eliminate exception by adding `@Primary` annotation to SpringRemoteCacheManagerFactoryBean.
Still have this warning:
`
2018-07-26 06:48:40.139  WARN 5 --- [           main] o.i.manager.DefaultCacheManager          : [] [] ISPN000435: Cache manager initialized with a default cache configuration but without a name for it. Set it in the GlobalConfiguration.
`
Doesn't look like clean initialization

**Comment by vadimkim** [comment]
As I understood there are still 2 CacheManagers initialized:
1. DefaultCacheManager
2. SpringRemoteCacheManager initialized by SpringRemoteCacheManagerFactoryBean which is now primary.

Can I (should I) eliminate DefaultCacheManager?

**Comment by slaskawi** [comment]
Indeed, it seems you're using at least 2 `CacheManager`s. The Infinispan Spring Boot Extension tries to automatically initialize `CacheManager` if it's not there (see (1)(2)). It looks like your setup doesn't need that, so you might turn it off by specifying `infinispan.embedded.enabled = false` and `infinispan.remote.enabled = false`.

(1) https://github.com/infinispan/infinispan-spring-boot/blob/master/infinispan-spring-boot-starter-embedded/src/main/java/org/infinispan/spring/starter/embedded/InfinispanEmbeddedAutoConfiguration.java#L57
(2) https://github.com/infinispan/infinispan-spring-boot/blob/master/infinispan-spring-boot-starter-remote/src/main/java/org/infinispan/spring/starter/remote/InfinispanRemoteCacheManagerAutoConfiguration.java#L18

**Comment by vadimkim** [comment]
That's worked like a charm! Thank you @slaskawi
